default: &default
  adapter: mysql2
  database: ototown_dev
  username: root
  password: 
  pool: 5
  timeout: 5000
  socket: /opt/lampp/var/mysql/mysql.sock

development:
  <<: *default
test:
  <<: *default
  database: ototown_test
