default: &default
  adapter: postgresql
  encoding: unicode
  database: ototown_dev
  pool: 5
  username: foobar
  password: 123123123

development:
  <<: *default
test:
  <<: *default
  database: ototown_test


# production:
#   adapter: postgresql
#   encoding: unicode
#   database: dfvl642u9eut4a
#   port: 5432
#   host: ec2-54-225-103-9.compute-1.amazonaws.com
#   username: xmkpriosmzhdsx
#   password: pa5LiOnHnyW2lhQniGCN2ici9n

